# Generated by Django 5.0.11 on 2025-02-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('maHoaDon', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('tongTien', models.IntegerField(default=0)),
                ('ngayTao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('timeslot', models.TimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VeDatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanhToan', models.BooleanField(default=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
