# Generated by Django 5.0.11 on 2025-02-16 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BBooking', '0001_initial'),
        ('BCourt', '0001_initial'),
        ('BUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='courtStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BUser.courtstaff'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='san',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.san'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBooking.timeslot'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='vedatsan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BBooking.vedatsan'),
        ),
        migrations.AlterUniqueTogether(
            name='vedatsan',
            unique_together={('san', 'date', 'timeslot')},
        ),
    ]
