# Generated by Django 5.0.11 on 2025-02-11 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BBooking', '0001_initial'),
        ('BCourt', '0001_initial'),
        ('BUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='courtStaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUser.courtstaff'),
        ),
        migrations.AddField(
            model_name='timeslotcourt',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court'),
        ),
        migrations.AddField(
            model_name='timeslotcourt',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBooking.timeslot'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='san',
            field=models.ManyToManyField(to='BCourt.san'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='timeslot',
            field=models.ManyToManyField(to='BBooking.timeslot'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='vedatsan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BBooking.vedatsan'),
        ),
        migrations.AddConstraint(
            model_name='timeslotcourt',
            constraint=models.UniqueConstraint(fields=('court', 'timeslot'), name='unique_Timeslot'),
        ),
    ]
