# Generated by Django 5.0.11 on 2025-02-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedatsan',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BBooking.voucher'),
        ),
    ]
