# Generated by Django 5.0.11 on 2025-02-19 17:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0002_initial'),
        ('BCourt', '0003_alter_court_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='flexTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
