# Generated by Django 5.0.11 on 2025-02-19 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0003_flextime'),
        ('BCourt', '0003_alter_court_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flextime',
            unique_together={('customer', 'court')},
        ),
    ]
