# Generated by Django 5.0.11 on 2025-02-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0004_alter_flextime_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedatsan',
            name='checkin',
            field=models.CharField(choices=[('chuacheckin', 'Chưa check-in'), ('dacheckin', 'Đã check-in')], default='chuacheckin', max_length=20),
        ),
    ]
