# Generated by Django 5.1.4 on 2025-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0005_alter_vedatsan_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='id',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
