# Generated by Django 5.0.11 on 2025-02-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('B_Court', '0001_initial'),
        ('B_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.court')),
            ],
        ),
        migrations.CreateModel(
            name='VeDatSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maVe', models.CharField(default='', max_length=255)),
                ('thanhToan', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.customer')),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.san')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Booking.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maHoaDon', models.CharField(default='', max_length=255)),
                ('tongTien', models.IntegerField(default=0)),
                ('ngayTao', models.DateTimeField()),
                ('note', models.CharField(default='', max_length=255)),
                ('courtStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.courtstaff')),
                ('vedatsan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Booking.vedatsan')),
            ],
        ),
    ]
