# Generated by Django 5.0.11 on 2025-02-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('B_Booking', '0001_initial'),
        ('B_Court', '0001_initial'),
        ('B_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='courtStaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.courtstaff'),
        ),
        migrations.AddField(
            model_name='timeslotcourt',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.court'),
        ),
        migrations.AddField(
            model_name='timeslotcourt',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Booking.timeslot'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.customer'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='san',
            field=models.ManyToManyField(to='B_Court.san'),
        ),
        migrations.AddField(
            model_name='vedatsan',
            name='timeslot',
            field=models.ManyToManyField(to='B_Booking.timeslot'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='vedatsan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='B_Booking.vedatsan'),
        ),
        migrations.AddConstraint(
            model_name='timeslotcourt',
            constraint=models.UniqueConstraint(fields=('court', 'timeslot'), name='unique_Timeslot'),
        ),
    ]
