# Generated by Django 5.0.11 on 2025-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maVip', models.CharField(default='', max_length=255)),
                ('diem', models.IntegerField(default=0)),
                ('lvVIP', models.IntegerField(default=0)),
                ('phanTramGiamGia', models.FloatField(default=0)),
            ],
        ),
    ]
