# Generated by Django 5.0.11 on 2025-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('maVip', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('diem', models.IntegerField(default=0)),
                ('lvVIP', models.IntegerField(default=0)),
                ('phanTramGiamGia', models.FloatField(default=0)),
            ],
        ),
    ]
