# Generated by Django 5.1.3 on 2025-02-18 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_courtstaff_days_worked_courtstaff_salary_per_day"),
    ]

    operations = [
        migrations.DeleteModel(
            name="staffRequest",
        ),
    ]
