# Generated by Django 5.1.3 on 2025-02-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_delete_staffrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourtStaff",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Đã Thanh Toán", "Đã Thanh Toán"),
                    ("Chưa Thanh Toán", "Chưa Thanh Toán"),
                ],
                default="Chưa Thanh Toán",
                max_length=50,
            ),
        ),
    ]
