# Generated by Django 5.1.4 on 2025-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaGiamGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma', models.CharField(max_length=255)),
                ('Giamgia', models.IntegerField(default=0)),
            ],
        ),
    ]
