# Generated by Django 5.1.4 on 2025-02-19 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBooking', '0003_magiamgia'),
        ('BCourt', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=10)),
                ('percent', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court')),
            ],
        ),
        migrations.DeleteModel(
            name='MaGiamGia',
        ),
    ]
