# Generated by Django 5.0.11 on 2025-02-10 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('B_Court', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtManager',
            fields=[
                ('roleId', models.IntegerField(default='1')),
                ('fullName', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('sdt', models.IntegerField(blank=True, default=0, null=True)),
                ('gmail', models.CharField(default='', max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('roleId', models.IntegerField(default='1')),
                ('fullName', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('sdt', models.IntegerField(blank=True, default=0, null=True)),
                ('gmail', models.CharField(default='', max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soNha', models.CharField(default='', max_length=255)),
                ('xa', models.CharField(default='', max_length=255)),
                ('huyen', models.CharField(default='', max_length=255)),
                ('tinh', models.CharField(default='', max_length=255)),
                ('quocGia', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourtStaff',
            fields=[
                ('roleId', models.IntegerField(default='1')),
                ('fullName', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('sdt', models.IntegerField(blank=True, default=0, null=True)),
                ('gmail', models.CharField(default='', max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='B_Court.court')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('soNha', 'xa', 'huyen', 'tinh', 'quocGia'), name='unique_position'),
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='B_User.position'),
        ),
    ]
