# Generated by Django 5.0.11 on 2025-02-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('B_Court', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.IntegerField(default='0')),
                ('useName', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soNha', models.CharField(default='', max_length=255)),
                ('huyen', models.CharField(default='', max_length=255)),
                ('tinh', models.CharField(default='', max_length=255)),
                ('quocGia', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourtManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdt', models.IntegerField(default=0)),
                ('gmail', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('fullName', models.CharField(default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.account')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.court')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourtStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdt', models.IntegerField(default=0)),
                ('gmail', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('fullName', models.CharField(default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.account')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.court')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdt', models.IntegerField(default=0)),
                ('gmail', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('fullName', models.CharField(default='', max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.account')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.position')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
