# Generated by Django 5.0.11 on 2025-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='xa',
            field=models.CharField(default='', max_length=255),
        ),
    ]
