# Generated by Django 5.0.11 on 2025-02-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_User', '0002_position_xa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roleId',
            field=models.IntegerField(default='1'),
        ),
    ]
