# Generated by Django 5.0.11 on 2025-02-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='San',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maSan', models.CharField(default='', max_length=255)),
                ('tinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maCourt', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('descreption', models.CharField(default='', max_length=255)),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.san')),
            ],
        ),
    ]
