# Generated by Django 5.0.11 on 2025-02-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('B_Court', '0001_initial'),
        ('B_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='courtManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_User.courtmanager'),
        ),
        migrations.AddField(
            model_name='san',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_Court.court'),
        ),
    ]
