# Generated by Django 5.0.11 on 2025-02-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soNha', models.CharField(default='', max_length=255)),
                ('xa', models.CharField(default='', max_length=255)),
                ('huyen', models.CharField(default='', max_length=255)),
                ('tinh', models.CharField(default='', max_length=255)),
                ('quocGia', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('maCourt', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('descreption', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='San',
            fields=[
                ('maSan', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('tinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('soNha', 'xa', 'huyen', 'tinh', 'quocGia'), name='unique_address'),
        ),
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BCourt.address'),
        ),
    ]
