# Generated by Django 5.0.11 on 2025-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('maCourt', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('img', models.ImageField(upload_to='images/', verbose_name='Hình ảnh sân')),
            ],
        ),
        migrations.CreateModel(
            name='Duong',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phuong',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='San',
            fields=[
                ('maSan', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('numSan', models.IntegerField()),
                ('tinhTrang', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sonha',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
