# Generated by Django 5.0.11 on 2025-02-19 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BCourt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='courtManager',
            field=models.ForeignKey(limit_choices_to={'role': 'courtmanager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='court',
            name='courtStaff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'courtstaff'}, related_name='staffed_courts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='san',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('court', 'customer')},
        ),
    ]
