# Generated by Django 5.0.11 on 2025-02-18 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BCourt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='courtManager',
            field=models.ForeignKey(limit_choices_to={'role': 'courtmanager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='court',
            name='courtStaff',
            field=models.ManyToManyField(limit_choices_to={'role': 'courtstaff'}, related_name='staffed_courts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phuong',
            name='duong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.duong'),
        ),
        migrations.AddField(
            model_name='quan',
            name='phuong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.phuong'),
        ),
        migrations.AddField(
            model_name='rating',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='san',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court'),
        ),
        migrations.AlterUniqueTogether(
            name='sonha',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='duong',
            name='sonha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.sonha'),
        ),
        migrations.AddField(
            model_name='tinh',
            name='quan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.quan'),
        ),
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BCourt.tinh'),
        ),
        migrations.AlterUniqueTogether(
            name='phuong',
            unique_together={('name', 'duong')},
        ),
        migrations.AlterUniqueTogether(
            name='quan',
            unique_together={('name', 'phuong')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('court', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='duong',
            unique_together={('name', 'sonha')},
        ),
        migrations.AlterUniqueTogether(
            name='tinh',
            unique_together={('name', 'quan')},
        ),
    ]
