# Generated by Django 5.0.11 on 2025-02-18 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='courtStaff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'courtstaff'}, related_name='staffed_courts', to=settings.AUTH_USER_MODEL),
        ),
    ]
