# Generated by Django 5.0.11 on 2025-02-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='san',
            name='tinhTrang',
        ),
    ]
