# Generated by Django 5.0.11 on 2025-02-19 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000)]),
        ),
    ]
