# Generated by Django 5.0.11 on 2025-02-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='img',
            field=models.ImageField(default=123, upload_to='images/'),
            preserve_default=False,
        ),
    ]
