# Generated by Django 5.0.11 on 2025-02-11 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0003_court_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='courtManager',
            field=models.ForeignKey(limit_choices_to={'role': 'courtmanager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='court',
            name='descreption',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
