# Generated by Django 5.1.3 on 2025-02-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BCourt", "0003_courtstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtstaff",
            name="days_worked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="courtstaff",
            name="salary_per_day",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
