# Generated by Django 5.1.3 on 2025-02-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BCourt", "0004_courtstaff_days_worked_courtstaff_salary_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bookings", models.IntegerField()),
            ],
        ),
    ]
