# Generated by Django 5.0.11 on 2025-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0004_alter_court_courtmanager_alter_court_descreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='san',
            name='numSan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
