# Generated by Django 5.1.4 on 2025-02-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0004_xinviec'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BCourt.court')),
            ],
        ),
    ]
