# Generated by Django 5.0.11 on 2025-02-16 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0004_alter_rating_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('court', 'customer')},
        ),
    ]
