# Generated by Django 5.1.4 on 2025-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0005_courttimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttimeslot',
            name='time',
            field=models.TimeField(),
        ),
    ]
