# Generated by Django 5.1.3 on 2025-02-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BCourt", "0006_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
