# Generated by Django 5.1.4 on 2025-02-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0006_duong_sonha_remove_court_address_phuong_quan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='court',
            name='Address',
        ),
        migrations.AlterField(
            model_name='court',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Hình ảnh sân'),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BCourt.tinh'),
        ),
    ]
