# Generated by Django 5.1.4 on 2025-02-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCourt', '0007_rename_descreption_court_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='address',
            new_name='tinh',
        ),
    ]
