# Generated by Django 5.1.3 on 2025-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BCourt", "0008_alter_transaction_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
            ],
        ),
    ]
