# Generated by Django 5.1.3 on 2025-02-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BUser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="day_worked",
            field=models.IntegerField(default=0),
        ),
    ]
