# Generated by Django 5.0.11 on 2025-02-19 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeFlex',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
