# Generated by Django 5.0.11 on 2025-02-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0002_user_timeflex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timeFlex',
        ),
    ]
